### ISSUE TITLE
Using justd-cli installs v1.x components

### ISSUE THREAD

**Issue by Thanzex** [justdlabs/cli#6]
I have a tailwind project, I tried installing justd with `npx justd-cli@latest init` and then importing the `Sidebar` layout with `npx justd-cli@latest add sidebar`.

I was a bit confused when typescript couldn't find `SidebarInset, SidebarProvider` from `ui` , then I went ahead and looked at the installed files, where the sidebar is exported as:
```
Sidebar.Provider = Provider
Sidebar.Inset = Inset
Sidebar.Header = Header
Sidebar.Nav = Nav
Sidebar.Content = Content
Sidebar.Footer = Footer
Sidebar.Item = Item
Sidebar.Section = Section
Sidebar.Rail = Rail
Sidebar.Trigger = Trigger
```

After observing the docs website, I can see this is the layout present in v1.

Is this intended behaviour? Is this a CLI problem?

PS. the docs website is completely broken when selecting v1.x

**Comment by irsyadadl** [comment]
What version you're trying? if you in tailwind v3, your docs in 1.x in https://getjustd.com/docs/1.x/components/layouts/sidebar

**Comment by irsyadadl** [comment]
Thanks for the report. Let me investigate this issue.

**Comment by irsyadadl** [comment]
hey @Thanzex , can you please try again. I've been made the fix version on it https://github.com/justdlabs/cli/releases/tag/v2.1.2, if it solved the problem, please close this issue.

**Comment by Thanzex** [comment]
Hi @irsyadadl , thanks for the response, unfortunately, I just installed `sidebar` again with the cli v2.1.4 and the file structure is the same

**Comment by irsyadadl** [comment]
@Thanzex what's wrong with the file structure? is that same as the docs on v1 https://getjustd.com/docs/1.x/components/layouts/sidebar

**Comment by Thanzex** [comment]
@irsyadadl Yes, i just thought it was strange since the documentation website defaults to 2.x but the cli installs 1.x.
At the time of writing the 1.x docs were not working properly, leading me to think they were somewhat abandoned or otherwise 'old'.

**Comment by irsyadadl** [comment]
I've just updated the docs for notice the docs for 2.x will assumes you're using tw3. And right now, I'll make the migration guide from 1.x to 2.x.

**Comment by Thanzex** [comment]
@irsyadadl Yes, i just thought it was strange since the documentation website defaults to 2.x but the cli installs 1.x.
At the time of writing the 1.x docs were not working properly, leading me to think they were somewhat abandoned or otherwise 'old'.

I see the warning banner on the 1.x website, but nothing on the 2.x. Maybe a little mention of  the 1.x docs for tailwind 3 could be appropriate.

I believe we can close this issue.
